web:
  build:
  links:
    - 'pg_db'
  ports:
    - '8000:8000'
  volumes:
    - './'
  environment:
    - 'DATABASE_HOST=pg_db'
    - 'DATABASE_NAME=wonder_emporium'
    - 'DATABASE_USER=wonder_emporium'
    - 'DATABASE_PASSWORD=wonder_emporium'
pg_db:
  image: postgres:9.6
