# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20170721_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=11, editable=False, max_digits=10),
            preserve_default=False,
        ),
    ]
