# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-06 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product__is_funny'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='_is_funny',
        ),
    ]
